# 全局配置
Index:
  Background: Build

Diagnostics:
  ClangTidy:
    Add:
      - "bugprone-*"
      - "performance-*"
      - "readability-*"
      - "modernize-*"
    Remove:
      - "modernize-use-trailing-return-type"
      - "readability-magic-numbers"
      - "readability-braces-around-statements"
  Suppress:
    - "drv_unknown_argument"

InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
  Designators: Yes
  BlockEnd: No
  DefaultArguments: Yes

---
# CUDA 对应文件的特定配置
If:
  PathMatch: [.*\.cu, .*\.cuh]
CompileFlags:
  Add:
    - "-xcuda"
    - "--cuda-path=/usr/local/cuda"
    - "-I/usr/local/cuda/include"
    - "--cuda-gpu-arch=sm_90"
    - "-nocudalib"
    - "--cuda-host-only"
  Remove:
    - "-arch=*"
    - "-forward-unknown-to-host-compiler"
    - "--generate-code=*"
    - "-Xcompiler=*"
    - "--extended-lambda"
    - "-rdc=*"
    - "-ccbin=*"
    - "-gencode=*"
    - "--expt-relaxed-constexpr"
    - "--expt-extended-lambda"
    - "--threads=*"
    - "--split-compile=*"
    - "--compress-mode=*"
    - "--Ofast-compile=*"
